import { TreeNode } from "../fs/treeManager.js";

function serializeValue(value: unknown): string | null {
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") {
    const escaped = value
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r");
    return `"${escaped}"`;
  }

  if (value !== null && typeof value === "object") {
    const v = value as Record<string, unknown>;
    switch (v.__type) {
      case "Color3":
        return `Color3.new(${v.r}, ${v.g}, ${v.b})`;
      case "Vector3":
        return `Vector3.new(${v.x}, ${v.y}, ${v.z})`;
      case "Vector2":
        return `Vector2.new(${v.x}, ${v.y})`;
      case "Vector2int16":
        return `Vector2int16.new(${v.x}, ${v.y})`;
      case "Vector3int16":
        return `Vector3int16.new(${v.x}, ${v.y}, ${v.z})`;
      case "UDim":
        return `UDim.new(${v.scale}, ${v.offset})`;
      case "UDim2":
        return `UDim2.new(${v.xScale}, ${v.xOffset}, ${v.yScale}, ${v.yOffset})`;
      case "CFrame": {
        const c = v.components as number[] | undefined;
        if (c && c.length >= 12) return `CFrame.new(${c.join(", ")})`;
        return null;
      }
      case "BrickColor":
        if (v.number !== undefined) return `BrickColor.new(${v.number})`;
        return null;
      case "EnumItem":
        if (v.enumType && v.name) return `Enum.${v.enumType}.${v.name}`;
        return null;
      case "Font":
        if (v.family) return `Font.new("${v.family}")`;
        return null;
      case "Rect":
        return `Rect.new(${v.minX}, ${v.minY}, ${v.maxX}, ${v.maxY})`;
      case "NumberRange":
        return `NumberRange.new(${v.min}, ${v.max})`;
      case "PhysicalProperties":
        return `PhysicalProperties.new(${v.density}, ${v.friction}, ${v.elasticity}, ${v.frictionWeight}, ${v.elasticityWeight})`;
    }
  }

  return null;
}

export function generateConstructorScript(node: TreeNode): string {
  const lines: string[] = [
    `-- Generated by Azul (scriptifyInstances)`,
    `local object = Instance.new("${node.className}")`,
  ];

  if (node.properties) {
    for (const [key, value] of Object.entries(node.properties)) {
      const serialized = serializeValue(value);
      if (serialized !== null) {
        lines.push(`object.${key} = ${serialized}`);
      }
    }
  }

  lines.push(`return object`);

  return lines.join("\n") + "\n";
}
