import { TreeNode } from "../fs/treeManager.js";

function serializeValue(value: unknown): string | null {
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") {
    const escaped = value
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r");
    return `"${escaped}"`;
  }

  if (value !== null && typeof value === "object") {
    const v = value as Record<string, unknown>;
    switch (v.Type) {
      case "Color3":
        return `Color3.new(${v.R}, ${v.G}, ${v.B})`;
      case "Vector3":
        return `Vector3.new(${v.X}, ${v.Y}, ${v.Z})`;
      case "Vector2":
        return `Vector2.new(${v.X}, ${v.Y})`;
      case "UDim":
        return `UDim.new(${v.Scale}, ${v.Offset})`;
      case "UDim2": {
        const x = v.X as Record<string, unknown> | undefined;
        const y = v.Y as Record<string, unknown> | undefined;
        return `UDim2.new(${x?.Scale}, ${x?.Offset}, ${y?.Scale}, ${y?.Offset})`;
      }
      case "CFrame": {
        const pos = v.Position as Record<string, unknown> | undefined;
        if (pos) return `CFrame.new(${pos.X}, ${pos.Y}, ${pos.Z})`;
        return null;
      }
      case "BrickColor":
        if (v.Name) return `BrickColor.new("${v.Name}")`;
        return null;
      case "EnumItem":
        if (v.EnumType && v.Name) return `Enum.${v.EnumType}.${v.Name}`;
        return null;
      case "Font":
        if (v.Family) return `Font.new("${v.Family}")`;
        return null;
    }
  }

  return null;
}

export function generateConstructorScript(node: TreeNode): string {
  const lines: string[] = [
    `-- Generated by Azul (scriptifyInstances)`,
    `local object = Instance.new("${node.className}")`,
  ];

  if (node.properties) {
    for (const [key, value] of Object.entries(node.properties)) {
      const serialized = serializeValue(value);
      if (serialized !== null) {
        lines.push(`object.${key} = ${serialized}`);
      }
    }
  }

  lines.push(`return object`);

  return lines.join("\n") + "\n";
}
